/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class IconClass */

#ifndef _Included_IconClass
#define _Included_IconClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     IconClass
 * Method:    OnButton1
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_IconClass_OnButton1
  (JNIEnv *, jclass);

/*
 * Class:     IconClass
 * Method:    OnButton2
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_IconClass_OnButton2
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
