version: 2
jobs:
  build:
    docker:
      - image: java:openjdk-8

    steps:
      - checkout

      - run:
          name: pmd
          command: |
            wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.11.0/pmd-bin-6.11.0.zip
            unzip pmd-bin-6.11.0.zip
            ./unzip -d . -R ruleset.xml